version: '3'

services:
  nodeserver:
    build:
      context: ./node
    image: luciomarcel/nodeserver
    container_name: nodeserver
    entrypoint: dockerize -wait tcp://db:3306 -timeout 20s  /usr/src/app/docker-entrypoint.sh
    networks:
      - node-network
    ports:
      - "3000:3000"
    volumes:
      - ./node:/usr/src/app
    tty: true
    depends_on:
      - db

  db:
    build:
      context:
        ./mysql
    image: luciomarcel/mysql:5.7
    container_name: mysqldb
    restart: always
    tty: true
    volumes:
      - ./mysql-data:/var/lib/mysql
    networks:
      - node-network
    command: --innodb-use-native-aio=0
    
  nginx:
    build: 
      context: ./nginx
    image: luciomarcel/nginxserver
    container_name: nginxserver
    networks:
      - node-network
    ports:
      - "8080:80"
    depends_on:
      - db

networks:
  node-network:
    driver: bridge